server:
  port: 9090
spring:
  datasource:
    password: 160103
    url: jdbc:mysql://localhost:3306/spring
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    banner-mode: 'off'
