spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: hr
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

